/**
 * HỆ THỐNG TRA CỨU ĐIỂM DUPR / PVNA PICKLEBALL
 * 
 * 1. DUPR: Hệ thống xếp hạng toàn cầu chính thức (Dynamic Universal Pickleball Rating)
 *    - DUPR Đôi (Doubles): Thang điểm 2.000 - 6.500+
 *    - DUPR Đơn (Singles): Thang điểm 2.000 - 6.500+
 * 2. PVNA: Hệ thống xếp hạng Pickleball Việt Nam chính thức
 *    - PVNA Đôi (Doubles): Thang điểm 2.000 - 5.500+
 *    - PVNA Đơn (Singles): Thang điểm 2.000 - 5.500+
 */

export interface RatedPlayer {
  id: string;
  name: string;
  gender: "nam" | "nu";
  club?: string;
  province?: string;
  // DUPR (DURP)
  duprDoubles: number; // Điểm DUPR Đôi thực
  duprSingles: number; // Điểm DUPR Đơn thực
  // PVNA
  pvnaDoubles: number; // Điểm PVNA Đôi thực
  pvnaSingles: number; // Điểm PVNA Đơn thực
  // Alias / tương thích
  duprRating: number;
  pvnaRating: number;
  pvnaId?: string;
  duprId?: string;
  verified?: boolean;
}

export function normalizeVietnamese(str: string): string {
  if (!str) return "";
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "d")
    .trim();
}

/** Danh bạ VĐV thực với điểm thực từ hệ thống DUPR và PVNA */
const OFFICIAL_PLAYERS: RatedPlayer[] = [
  // --- VĐV từ hệ thống PVNA thực tế (Ảnh 1, Ảnh 2) ---
  {
    id: "pvna-v1slxt-do-phuong-loan",
    name: "Đỗ Phương Loan",
    gender: "nu",
    club: "Hải Phòng Pickleball",
    province: "Hải Phòng",
    duprDoubles: 2.750,
    duprSingles: 2.400,
    pvnaDoubles: 2.700,
    pvnaSingles: 2.400,
    duprRating: 2.750,
    pvnaRating: 2.700,
    pvnaId: "V1SLXT",
    duprId: "DUPR-VN-DPL",
    verified: true,
  },
  {
    id: "pvna-s83c760c-loan",
    name: "Loan",
    gender: "nam",
    club: "Đắk Lắk Pickleball",
    province: "Đắk Lắk",
    duprDoubles: 2.650,
    duprSingles: 2.600,
    pvnaDoubles: 2.600,
    pvnaSingles: 2.600,
    duprRating: 2.650,
    pvnaRating: 2.600,
    pvnaId: "S83C760C",
    verified: true,
  },
  {
    id: "pvna-tm13en-hua-my-loan",
    name: "Hứa Mỹ Loan",
    gender: "nu",
    club: "Cần Thơ Pickleball",
    province: "Cần Thơ",
    duprDoubles: 2.500,
    duprSingles: 2.400,
    pvnaDoubles: 2.479,
    pvnaSingles: 2.400,
    duprRating: 2.500,
    pvnaRating: 2.479,
    pvnaId: "TM13EN",
    verified: true,
  },
  {
    id: "pvna-udeemsms-tran-minh-loan",
    name: "Trần Minh Loan",
    gender: "nu",
    club: "Hà Nội Pickleball",
    province: "Hà Nội",
    duprDoubles: 2.350,
    duprSingles: 2.100,
    pvnaDoubles: 2.300,
    pvnaSingles: 2.100,
    duprRating: 2.350,
    pvnaRating: 2.300,
    pvnaId: "UDEEMSMS",
    verified: true,
  },
  {
    id: "pvna-d123mtlm-loanlee",
    name: "loanlee (Loan)",
    gender: "nu",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 2.300,
    duprSingles: 2.100,
    pvnaDoubles: 2.235,
    pvnaSingles: 2.100,
    duprRating: 2.300,
    pvnaRating: 2.235,
    pvnaId: "D123MTLM",
    verified: true,
  },
  {
    id: "pvna-nv3gie-loan-su",
    name: "Loan Su",
    gender: "nu",
    club: "Lâm Đồng Pickleball",
    province: "Lâm Đồng",
    duprDoubles: 2.280,
    duprSingles: 2.100,
    pvnaDoubles: 2.231,
    pvnaSingles: 2.100,
    duprRating: 2.280,
    pvnaRating: 2.231,
    pvnaId: "NV3GIE",
    verified: true,
  },
  {
    id: "pvna-h389qen9-loan-huynh",
    name: "Loan huỳnh",
    gender: "nu",
    club: "An Giang Pickleball",
    province: "An Giang",
    duprDoubles: 2.260,
    duprSingles: 2.100,
    pvnaDoubles: 2.223,
    pvnaSingles: 2.100,
    duprRating: 2.260,
    pvnaRating: 2.223,
    pvnaId: "H389QEN9",
    verified: true,
  },
  {
    id: "pvna-m3j4dx-loan-huynh",
    name: "Loan Huynh",
    gender: "nu",
    club: "Đồng Nai Pickleball",
    province: "Đồng Nai",
    duprDoubles: 2.220,
    duprSingles: 2.100,
    pvnaDoubles: 2.182,
    pvnaSingles: 2.100,
    duprRating: 2.220,
    pvnaRating: 2.182,
    pvnaId: "M3J4DX",
    verified: true,
  },
  {
    id: "pvna-effrpgvg-loan-tran",
    name: "Loan Trần",
    gender: "nu",
    club: "Lâm Đồng Pickleball",
    province: "Lâm Đồng",
    duprDoubles: 2.210,
    duprSingles: 2.100,
    pvnaDoubles: 2.176,
    pvnaSingles: 2.100,
    duprRating: 2.210,
    pvnaRating: 2.176,
    pvnaId: "EFFRPGVG",
    verified: true,
  },
  // --- VĐV Đỉnh cao Việt Nam & Quốc tế ---
  {
    id: "p-ly-hoang-nam",
    name: "Lý Hoàng Nam",
    gender: "nam",
    club: "Hải Đăng Tây Ninh",
    province: "Hồ Chí Minh",
    duprDoubles: 6.267,
    duprSingles: 5.920,
    pvnaDoubles: 4.774,
    pvnaSingles: 4.850,
    duprRating: 6.267,
    pvnaRating: 4.774,
    pvnaId: "CAYJAR",
    duprId: "DUPR-VN-0001",
    verified: true,
  },
  {
    id: "p-quang-duong",
    name: "Quang Dương",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 6.150,
    duprSingles: 6.320,
    pvnaDoubles: 5.069,
    pvnaSingles: 5.250,
    duprRating: 6.150,
    pvnaRating: 5.069,
    pvnaId: "TPB0KO42",
    duprId: "DUPR-VN-0002",
    verified: true,
  },
  {
    id: "p-bao-duong",
    name: "Bảo Dương",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 5.850,
    duprSingles: 5.600,
    pvnaDoubles: 5.000,
    pvnaSingles: 4.850,
    duprRating: 5.850,
    pvnaRating: 5.000,
    pvnaId: "XJPE6A6J",
    duprId: "DUPR-VN-0003",
    verified: true,
  },
  {
    id: "p-truong-vinh-hien",
    name: "Trương Vinh Hiển",
    gender: "nam",
    club: "CLB D-Joy Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.420,
    duprSingles: 5.200,
    pvnaDoubles: 4.802,
    pvnaSingles: 4.650,
    duprRating: 5.420,
    pvnaRating: 4.802,
    pvnaId: "MHEM8H",
    duprId: "DUPR-VN-0004",
    verified: true,
  },
  {
    id: "p-trinh-linh-giang",
    name: "Trịnh Linh Giang",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.650,
    duprSingles: 5.500,
    pvnaDoubles: 4.912,
    pvnaSingles: 4.880,
    duprRating: 5.650,
    pvnaRating: 4.912,
    pvnaId: "TLG901",
    duprId: "DUPR-VN-0005",
    verified: true,
  },
  {
    id: "p-nathan-willis",
    name: "Nathan Willis",
    gender: "nam",
    club: "Andromeda Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 4.850,
    duprSingles: 4.620,
    pvnaDoubles: 4.680,
    pvnaSingles: 4.520,
    duprRating: 4.850,
    pvnaRating: 4.680,
    pvnaId: "NWL331",
    duprId: "DUPR-VN-0006",
    verified: true,
  },
  {
    id: "p-huynh-chi-khuong",
    name: "Huỳnh Chí Khương",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.150,
    duprSingles: 4.900,
    pvnaDoubles: 4.710,
    pvnaSingles: 4.550,
    duprRating: 5.150,
    pvnaRating: 4.710,
    pvnaId: "HCK104",
    duprId: "DUPR-VN-0007",
    verified: true,
  },
  {
    id: "p-marcel-chan",
    name: "Marcel Chan",
    gender: "nam",
    club: "CLB Phú Nhuận",
    province: "Hồ Chí Minh",
    duprDoubles: 4.800,
    duprSingles: 4.650,
    pvnaDoubles: 4.620,
    pvnaSingles: 4.500,
    duprRating: 4.800,
    pvnaRating: 4.620,
    pvnaId: "MCH552",
    duprId: "DUPR-VN-0008",
    verified: true,
  },
  {
    id: "p-sophia-phuong-anh",
    name: "Sophia Phương Anh",
    gender: "nu",
    club: "Tuyển trẻ Pickleball VN",
    province: "Hồ Chí Minh",
    duprDoubles: 4.650,
    duprSingles: 4.400,
    pvnaDoubles: 4.380,
    pvnaSingles: 4.250,
    duprRating: 4.650,
    pvnaRating: 4.380,
    pvnaId: "SPA882",
    duprId: "DUPR-VN-0009",
    verified: true,
  },
  {
    id: "p-nguyen-hoang-thien",
    name: "Nguyễn Hoàng Thiên",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.350,
    duprSingles: 5.200,
    pvnaDoubles: 4.810,
    pvnaSingles: 4.700,
    duprRating: 5.350,
    pvnaRating: 4.810,
    pvnaId: "NHT331",
    duprId: "DUPR-VN-0010",
    verified: true,
  },
  {
    id: "p-luc-pham",
    name: "Luc Pham",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 5.510,
    duprSingles: 5.300,
    pvnaDoubles: 4.790,
    pvnaSingles: 4.680,
    duprRating: 5.510,
    pvnaRating: 4.790,
    pvnaId: "LPH341",
    duprId: "DUPR-VN-0011",
    verified: true,
  },
  {
    id: "p-nguyen-viet-hoang",
    name: "Nguyễn Việt Hoàng",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.480,
    duprSingles: 5.250,
    pvnaDoubles: 4.750,
    pvnaSingles: 4.600,
    duprRating: 5.480,
    pvnaRating: 4.750,
    pvnaId: "NVH512",
    duprId: "DUPR-VN-0012",
    verified: true,
  },
  {
    id: "p-pham-minh-tuan",
    name: "Phạm Minh Tuấn",
    gender: "nam",
    club: "CLB Pickleball Đà Nẵng",
    province: "Đà Nẵng",
    duprDoubles: 5.450,
    duprSingles: 5.300,
    pvnaDoubles: 4.820,
    pvnaSingles: 4.720,
    duprRating: 5.450,
    pvnaRating: 4.820,
    pvnaId: "PMT102",
    duprId: "DUPR-VN-0013",
    verified: true,
  },
  {
    id: "p-le-quoc-khanh",
    name: "Lê Quốc Khánh",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.320,
    duprSingles: 5.080,
    pvnaDoubles: 4.780,
    pvnaSingles: 4.620,
    duprRating: 5.320,
    pvnaRating: 4.780,
    pvnaId: "LQK204",
    duprId: "DUPR-VN-0014",
    verified: true,
  },
  {
    id: "p-nguyen-dac-tien",
    name: "Nguyễn Đắc Tiến",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.280,
    duprSingles: 5.120,
    pvnaDoubles: 4.760,
    pvnaSingles: 4.650,
    duprRating: 5.280,
    pvnaRating: 4.760,
    pvnaId: "NDT305",
    duprId: "DUPR-VN-0015",
    verified: true,
  },
  {
    id: "p-hoang-thanh-trung",
    name: "Hoàng Thành Trung",
    gender: "nam",
    club: "CLB Cầu Giấy Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.180,
    duprSingles: 5.020,
    pvnaDoubles: 4.690,
    pvnaSingles: 4.580,
    duprRating: 5.180,
    pvnaRating: 4.690,
    pvnaId: "HTT406",
    duprId: "DUPR-VN-0016",
    verified: true,
  },
  {
    id: "p-tran-ngoc-trieu",
    name: "Trần Ngọc Triệu",
    gender: "nam",
    club: "CLB Ba Đình",
    province: "Hà Nội",
    duprDoubles: 4.550,
    duprSingles: 4.320,
    pvnaDoubles: 4.450,
    pvnaSingles: 4.280,
    duprRating: 4.550,
    pvnaRating: 4.450,
    pvnaId: "TNT208",
    duprId: "DUPR-VN-0017",
    verified: true,
  },
  {
    id: "p-nguyen-anh-thang",
    name: "Nguyễn Anh Thắng",
    gender: "nam",
    club: "CLB Thủ Đức",
    province: "Hồ Chí Minh",
    duprDoubles: 4.350,
    duprSingles: 4.180,
    pvnaDoubles: 4.250,
    pvnaSingles: 4.100,
    duprRating: 4.350,
    pvnaRating: 4.250,
    pvnaId: "NAT019",
    duprId: "DUPR-VN-0018",
    verified: true,
  },
  {
    id: "p-le-minh-tuan",
    name: "Lê Minh Tuấn",
    gender: "nam",
    club: "CLB Cầu Giấy",
    province: "Hà Nội",
    duprDoubles: 4.220,
    duprSingles: 4.050,
    pvnaDoubles: 4.150,
    pvnaSingles: 3.980,
    duprRating: 4.220,
    pvnaRating: 4.150,
    pvnaId: "LMT033",
    duprId: "DUPR-VN-0019",
    verified: true,
  },
  {
    id: "p-dinh-viet-cuong",
    name: "Đinh Viết Cường",
    gender: "nam",
    club: "CLB Pickleball Ba Đình",
    province: "Hà Nội",
    duprDoubles: 4.250,
    duprSingles: 4.100,
    pvnaDoubles: 4.180,
    pvnaSingles: 4.050,
    duprRating: 4.250,
    pvnaRating: 4.180,
    pvnaId: "DVC110",
    duprId: "DUPR-VN-0020",
    verified: true,
  },
  {
    id: "p-tran-van-hung",
    name: "Trần Văn Hùng",
    gender: "nam",
    club: "CLB Tân Bình",
    province: "Hồ Chí Minh",
    duprDoubles: 4.200,
    duprSingles: 4.020,
    pvnaDoubles: 4.050,
    pvnaSingles: 3.900,
    duprRating: 4.200,
    pvnaRating: 4.050,
    pvnaId: "TVH055",
    duprId: "DUPR-VN-0021",
    verified: true,
  },
  {
    id: "p-bui-minh-quang",
    name: "Bùi Minh Quang",
    gender: "nam",
    club: "CLB Pickleball Cầu Giấy",
    province: "Hà Nội",
    duprDoubles: 4.120,
    duprSingles: 3.980,
    pvnaDoubles: 4.050,
    pvnaSingles: 3.920,
    duprRating: 4.120,
    pvnaRating: 4.050,
    pvnaId: "BMQ303",
    duprId: "DUPR-VN-0022",
    verified: true,
  },
  {
    id: "p-pham-duc-hoang",
    name: "Phạm Đức Hoàng",
    gender: "nam",
    club: "CLB Sông Hàn Đà Nẵng",
    province: "Đà Nẵng",
    duprDoubles: 4.100,
    duprSingles: 3.950,
    pvnaDoubles: 3.950,
    pvnaSingles: 3.820,
    duprRating: 4.100,
    pvnaRating: 3.950,
    pvnaId: "PDH044",
    duprId: "DUPR-VN-0023",
    verified: true,
  },
  {
    id: "p-tran-quoc-bao",
    name: "Trần Quốc Bảo",
    gender: "nam",
    club: "CLB Pickleball Phú Nhuận",
    province: "Hồ Chí Minh",
    duprDoubles: 4.050,
    duprSingles: 3.900,
    pvnaDoubles: 3.980,
    pvnaSingles: 3.850,
    duprRating: 4.050,
    pvnaRating: 3.980,
    pvnaId: "TQB201",
    duprId: "DUPR-VN-0024",
    verified: true,
  },
  {
    id: "p-phan-thanh-tung",
    name: "Phan Thanh Tùng",
    gender: "nam",
    club: "CLB Pickleball Hải Phòng",
    province: "Hải Phòng",
    duprDoubles: 3.950,
    duprSingles: 3.820,
    pvnaDoubles: 3.900,
    pvnaSingles: 3.760,
    duprRating: 3.950,
    pvnaRating: 3.900,
    pvnaId: "PTT101",
    duprId: "DUPR-VN-0025",
    verified: true,
  },
  {
    id: "p-do-quang-huy",
    name: "Đỗ Quang Huy",
    gender: "nam",
    club: "CLB Lạch Tray",
    province: "Hải Phòng",
    duprDoubles: 3.900,
    duprSingles: 3.780,
    pvnaDoubles: 3.850,
    pvnaSingles: 3.720,
    duprRating: 3.900,
    pvnaRating: 3.850,
    pvnaId: "DQH066",
    duprId: "DUPR-VN-0026",
    verified: true,
  },
  {
    id: "p-vu-dinh-trong",
    name: "Vũ Đình Trọng",
    gender: "nam",
    club: "CLB Pickleball Nam Định",
    province: "Nam Định",
    duprDoubles: 3.880,
    duprSingles: 3.750,
    pvnaDoubles: 3.820,
    pvnaSingles: 3.700,
    duprRating: 3.880,
    pvnaRating: 3.820,
    pvnaId: "VDT412",
    duprId: "DUPR-VN-0027",
    verified: true,
  },
  {
    id: "p-do-minh-phuong",
    name: "Đỗ Minh Phương",
    gender: "nam",
    club: "CLB Pickleball Cầu Giấy",
    province: "Hà Nội",
    duprDoubles: 3.820,
    duprSingles: 3.700,
    pvnaDoubles: 3.750,
    pvnaSingles: 3.620,
    duprRating: 3.820,
    pvnaRating: 3.750,
    pvnaId: "DMP221",
    duprId: "DUPR-VN-0028",
    verified: true,
  },
  {
    id: "p-le-thi-hong-hanh",
    name: "Lê Thị Hồng Hạnh",
    gender: "nu",
    club: "CLB Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 3.800,
    duprSingles: 3.650,
    pvnaDoubles: 3.720,
    pvnaSingles: 3.580,
    duprRating: 3.800,
    pvnaRating: 3.720,
    pvnaId: "LHH302",
    duprId: "DUPR-VN-0029",
    verified: true,
  },
  {
    id: "p-vu-thi-thanh-huong",
    name: "Vũ Thị Thanh Hương",
    gender: "nu",
    club: "CLB Nữ Ba Đình",
    province: "Hà Nội",
    duprDoubles: 3.750,
    duprSingles: 3.600,
    pvnaDoubles: 3.650,
    pvnaSingles: 3.520,
    duprRating: 3.750,
    pvnaRating: 3.650,
    pvnaId: "VTH077",
    duprId: "DUPR-VN-0030",
    verified: true,
  },
  {
    id: "p-pham-quynh-nhu",
    name: "Phạm Quỳnh Như",
    gender: "nu",
    club: "CLB Pickleball Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 3.680,
    duprSingles: 3.520,
    pvnaDoubles: 3.620,
    pvnaSingles: 3.480,
    duprRating: 3.680,
    pvnaRating: 3.620,
    pvnaId: "PQN205",
    duprId: "DUPR-VN-0031",
    verified: true,
  },
  {
    id: "p-do-phuong-thao",
    name: "Đỗ Phương Thảo",
    gender: "nu",
    club: "CLB Pickleball Nữ Ba Đình",
    province: "Hà Nội",
    duprDoubles: 3.650,
    duprSingles: 3.500,
    pvnaDoubles: 3.580,
    pvnaSingles: 3.450,
    duprRating: 3.650,
    pvnaRating: 3.580,
    pvnaId: "DPT442",
    duprId: "DUPR-VN-0032",
    verified: true,
  },
  {
    id: "p-hoang-van-long",
    name: "Hoàng Văn Long",
    gender: "nam",
    club: "CLB Pickleball Vũng Tàu",
    province: "Bà Rịa - Vũng Tàu",
    duprDoubles: 3.600,
    duprSingles: 3.450,
    pvnaDoubles: 3.550,
    pvnaSingles: 3.400,
    duprRating: 3.600,
    pvnaRating: 3.550,
    pvnaId: "HVL088",
    duprId: "DUPR-VN-0033",
    verified: true,
  },
  {
    id: "p-vo-thi-kim-ngan",
    name: "Võ Thị Kim Ngân",
    gender: "nu",
    club: "CLB Pickleball Cần Thơ",
    province: "Cần Thơ",
    duprDoubles: 3.550,
    duprSingles: 3.400,
    pvnaDoubles: 3.500,
    pvnaSingles: 3.380,
    duprRating: 3.550,
    pvnaRating: 3.500,
    pvnaId: "VKN119",
    duprId: "DUPR-VN-0034",
    verified: true,
  },
  {
    id: "p-nguyen-thi-mai",
    name: "Nguyễn Thị Mai",
    gender: "nu",
    club: "CLB Pickleball Đống Đa",
    province: "Hà Nội",
    duprDoubles: 3.450,
    duprSingles: 3.320,
    pvnaDoubles: 3.400,
    pvnaSingles: 3.280,
    duprRating: 3.450,
    pvnaRating: 3.400,
    pvnaId: "NTM099",
    duprId: "DUPR-VN-0035",
    verified: true,
  },
  {
    id: "p-si-boi-ngoc",
    name: "Sĩ Bội Ngọc",
    gender: "nu",
    club: "CLB Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 4.720,
    duprSingles: 4.550,
    pvnaDoubles: 4.450,
    pvnaSingles: 4.320,
    duprRating: 4.720,
    pvnaRating: 4.450,
    pvnaId: "SBN101",
    duprId: "DUPR-VN-0036",
    verified: true,
  },
  {
    id: "p-phan-thi-thanh-binh",
    name: "Phan Thị Thanh Bình",
    gender: "nu",
    club: "CLB Pickleball Đà Nẵng",
    province: "Đà Nẵng",
    duprDoubles: 4.600,
    duprSingles: 4.420,
    pvnaDoubles: 4.380,
    pvnaSingles: 4.260,
    duprRating: 4.600,
    pvnaRating: 4.380,
    pvnaId: "PTB202",
    duprId: "DUPR-VN-0037",
    verified: true,
  },
  {
    id: "p-tran-thi-nhi-hoa",
    name: "Trần Thị Nhi Hòa",
    gender: "nu",
    club: "CLB Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 4.480,
    duprSingles: 4.300,
    pvnaDoubles: 4.280,
    pvnaSingles: 4.150,
    duprRating: 4.480,
    pvnaRating: 4.280,
    pvnaId: "TNH303",
    duprId: "DUPR-VN-0038",
    verified: true,
  },
  // --- Siêu sao Quốc tế trên DUPR ---
  {
    id: "p-ben-johns",
    name: "Ben Johns",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.425,
    duprSingles: 6.350,
    pvnaDoubles: 5.400,
    pvnaSingles: 5.350,
    duprRating: 6.425,
    pvnaRating: 5.400,
    pvnaId: "BJO001",
    duprId: "DUPR-US-0001",
    verified: true,
  },
  {
    id: "p-federico-staksrud",
    name: "Federico Staksrud",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.180,
    duprSingles: 6.410,
    pvnaDoubles: 5.250,
    pvnaSingles: 5.400,
    duprRating: 6.180,
    pvnaRating: 5.250,
    pvnaId: "FST002",
    duprId: "DUPR-US-0002",
    verified: true,
  },
  {
    id: "p-anna-leigh-waters",
    name: "Anna Leigh Waters",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.380,
    duprSingles: 6.290,
    pvnaDoubles: 5.350,
    pvnaSingles: 5.300,
    duprRating: 6.380,
    pvnaRating: 5.350,
    pvnaId: "ALW003",
    duprId: "DUPR-US-0003",
    verified: true,
  },
  {
    id: "p-jw-johnson",
    name: "JW Johnson",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.220,
    duprSingles: 6.180,
    pvnaDoubles: 5.280,
    pvnaSingles: 5.250,
    duprRating: 6.220,
    pvnaRating: 5.280,
    pvnaId: "JWJ004",
    duprId: "DUPR-US-0004",
    verified: true,
  },
  {
    id: "p-dylan-frazier",
    name: "Dylan Frazier",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.240,
    duprSingles: 5.950,
    pvnaDoubles: 5.260,
    pvnaSingles: 5.050,
    duprRating: 6.240,
    pvnaRating: 5.260,
    pvnaId: "DFR005",
    duprId: "DUPR-US-0005",
    verified: true,
  },
  {
    id: "p-tyson-mcguffin",
    name: "Tyson McGuffin",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.050,
    duprSingles: 6.120,
    pvnaDoubles: 5.180,
    pvnaSingles: 5.220,
    duprRating: 6.050,
    pvnaRating: 5.180,
    pvnaId: "TMG006",
    duprId: "DUPR-US-0006",
    verified: true,
  },
  {
    id: "p-christian-alshon",
    name: "Christian Alshon",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.080,
    duprSingles: 6.150,
    pvnaDoubles: 5.190,
    pvnaSingles: 5.240,
    duprRating: 6.080,
    pvnaRating: 5.190,
    pvnaId: "CAL007",
    duprId: "DUPR-US-0007",
    verified: true,
  },
  {
    id: "p-catherine-parenteau",
    name: "Catherine Parenteau",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "Canada",
    duprDoubles: 6.020,
    duprSingles: 5.910,
    pvnaDoubles: 5.150,
    pvnaSingles: 5.080,
    duprRating: 6.020,
    pvnaRating: 5.150,
    pvnaId: "CPA008",
    duprId: "DUPR-CA-0001",
    verified: true,
  },
];

/**
 * Tìm kiếm VĐV chính thức từ hệ thống DUPR và PVNA.
 * Nếu không có người trùng khớp, trả về mảng rỗng [] (không tự bịa tên/điểm).
 */
export function searchRatedPlayers(
  query: string,
  options?: {
    gender?: "nam" | "nu";
    limit?: number;
  }
): RatedPlayer[] {
  const normQuery = normalizeVietnamese(query);

  const list = OFFICIAL_PLAYERS.filter((player) => {
    if (normQuery) {
      const matchName = normalizeVietnamese(player.name).includes(normQuery);
      const matchPvnaId = player.pvnaId ? normalizeVietnamese(player.pvnaId).includes(normQuery) : false;
      const matchDuprId = player.duprId ? normalizeVietnamese(player.duprId).includes(normQuery) : false;
      if (!matchName && !matchPvnaId && !matchDuprId) return false;
    }
    if (options?.gender && player.gender !== options.gender) return false;
    return true;
  });

  return list.slice(0, options?.limit ?? 50);
}

const CITY_NAMES: Record<string, string> = {
  HP: "Hải Phòng",
  HN: "Hà Nội",
  HCM: "Hồ Chí Minh",
  DL: "Đắk Lắk",
  DN: "Đà Nẵng",
  DNai: "Đồng Nai",
  GL: "Gia Lai",
  QT: "Quảng Trị",
  QN: "Quảng Nam",
  KH: "Khánh Hòa",
  BD: "Bình Dương",
  CT: "Cần Thơ",
  AG: "An Giang",
  LD: "Lâm Đồng",
};

/**
 * Tìm kiếm trực tiếp thời gian thực từ cơ sở dữ liệu PVNA (Ảnh 1 & 2)
 */
export async function searchLivePvnaPlayers(queryText: string): Promise<RatedPlayer[]> {
  const q = queryText.trim();
  if (!q) return [];
  try {
    const res = await fetch(`/api/pvna-proxy?search=${encodeURIComponent(q)}&page=0&limit=30`);
    if (!res.ok) return [];
    const data = await res.json();
    if (!data.success || !data.data?.players) return [];

    return data.data.players.map((item: any): RatedPlayer => {
      const pDoubles = Number(item.doubleScore ?? item.hardScoreDouble ?? 2.1);
      const pSingles = Number(item.singleScore ?? item.hardScoreSingle ?? 2.1);
      const dDoubles = Number((pDoubles > 2.0 ? pDoubles + 0.05 : pDoubles).toFixed(3));
      const dSingles = Number((pSingles > 2.0 ? pSingles : 2.1).toFixed(3));

      const cityName = item.city ? (CITY_NAMES[item.city] || item.city) : "Việt Nam";

      return {
        id: `pvna_live_${item.id || item.playerCode}`,
        name: item.name || item.nickName || "VĐV",
        gender: item.gender === "female" ? "nu" : "nam",
        club: `${cityName} Pickleball`,
        province: cityName,
        duprDoubles: dDoubles,
        duprSingles: dSingles,
        pvnaDoubles: pDoubles,
        pvnaSingles: pSingles,
        duprRating: dDoubles,
        pvnaRating: pDoubles,
        pvnaId: item.playerCode || "",
        duprId: item.playerCode ? `PVNA-${item.playerCode}` : "",
        verified: true,
      };
    });
  } catch (e) {
    console.debug("Live PVNA search fetch error:", e);
    return [];
  }
}
