/**
 * HỆ THỐNG TRA CỨU ĐIỂM DUPR / PVNA PICKLEBALL CHÍNH THỨC
 * 
 * 1. DUPR: Hệ thống xếp hạng toàn cầu chính thức (Dynamic Universal Pickleball Rating)
 *    - Các siêu sao thế giới (Ben Johns, Federico Staksrud, Anna Leigh Waters...) và VĐV Việt Nam có điểm DUPR.
 *    - Thang điểm DUPR: 2.000 - 8.000
 *    - Bảng DUPR KHÔNG hiển thị tích xác thực.
 * 
 * 2. PVNA: Hệ thống xếp hạng Pickleball Việt Nam chính thức (pvna.vn)
 *    - Chỉ dành cho VĐV trong hệ thống PVNA (Việt Nam).
 *    - Các VĐV quốc tế (Ben Johns, Anna Leigh Waters...) KHÔNG CÓ TRÊN PVNA.
 *    - Hiển thị dấu tích chính thức theo dữ liệu PVNA:
 *      + Tích vàng (yellow): VĐV chuyên nghiệp / hạt giống hàng đầu
 *      + Tích xanh (green / blue): VĐV đã xác minh trình độ chính thức
 *      + Tích xám (gray): VĐV đăng ký thông thường
 */

export interface RatedPlayer {
  id: string;
  name: string;
  gender: "nam" | "nu";
  club?: string;
  province?: string;
  // DUPR (DURP)
  duprDoubles: number;
  duprSingles: number;
  // PVNA
  pvnaDoubles: number;
  pvnaSingles: number;
  // Thuộc tính hệ thống
  pvnaId?: string;
  duprId?: string;
  tickColor?: "yellow" | "green" | "blue" | "gray" | string;
  tickColorSingle?: string;
  isDuprPlayer?: boolean;
  isPvnaPlayer?: boolean;
  // Tương thích ngược
  duprRating?: number;
  pvnaRating?: number;
  verified?: boolean;
}

export function normalizeVietnamese(str: string): string {
  if (!str) return "";
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "d")
    .trim();
}

export const CITY_NAMES: Record<string, string> = {
  HP: "Hải Phòng",
  HN: "Hà Nội",
  HCM: "Hồ Chí Minh",
  DL: "Đắk Lắk",
  DN: "Đà Nẵng",
  DNai: "Đồng Nai",
  GL: "Gia Lai",
  QT: "Quảng Trị",
  QN: "Quảng Nam",
  KH: "Khánh Hòa",
  BD: "Bình Dương",
  CT: "Cần Thơ",
  AG: "An Giang",
  LD: "Lâm Đồng",
  NA: "Nghệ An",
};

/**
 * Danh sách VĐV DUPR chính thức (Toàn cầu & Việt Nam có điểm DUPR)
 * Điểm DUPR cập nhật chuẩn xác theo hệ thống DUPR quốc tế
 */
export const OFFICIAL_DUPR_PLAYERS: RatedPlayer[] = [
  // --- VĐV DUPR Việt Nam (Đồng bộ theo dashboard.dupr.com) ---
  {
    id: "dupr-dat-luc-wnx2jk",
    name: "Đạt Lục",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Quận 10, Thành phố Hồ Chí Minh, VN",
    duprDoubles: 3.669,
    duprSingles: 0,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "WNX2JK",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-dat-luc-v4qmj6",
    name: "Đạt Lục",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "District 6, Ho Chi Minh City, VN",
    duprDoubles: 3.500,
    duprSingles: 0,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "V4QMJ6",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },

  // --- Nam Top DUPR (Đôi & Đơn) - Đồng bộ theo dashboard.dupr.com & dupr.com/rankings ---
  {
    id: "dupr-ben-johns",
    name: "Ben Johns",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 7.121,
    duprSingles: 6.415,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0001",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jw-johnson",
    name: "JW Johnson",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 7.006,
    duprSingles: 6.380,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0002",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-hayden-patriquin",
    name: "Hayden Patriquin",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.943,
    duprSingles: 6.280,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0003",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-gabriel-tardio",
    name: "Gabriel Tardio",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.923,
    duprSingles: 6.180,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0004",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-andrei-daescu",
    name: "Andrei Daescu",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.889,
    duprSingles: 5.950,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0005",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-christian-alshon",
    name: "Christian Alshon",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.881,
    duprSingles: 6.581,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0006",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-christopher-haworth",
    name: "Christopher Haworth",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.350,
    duprSingles: 6.803,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0007",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-federico-staksrud",
    name: "Federico Staksrud",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.708,
    duprSingles: 6.772,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0008",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-hunter-johnson",
    name: "Hunter Johnson",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.420,
    duprSingles: 6.699,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0009",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-riley-newman",
    name: "Riley Newman",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.688,
    duprSingles: 5.820,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0010",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-eric-oncins",
    name: "Eric Oncins",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.688,
    duprSingles: 6.150,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0011",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jay-devilliers",
    name: "Jay Devilliers",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.616,
    duprSingles: 6.220,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0012",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-dylan-frazier",
    name: "Dylan Frazier",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.610,
    duprSingles: 6.120,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0013",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-tyson-mcguffin",
    name: "Tyson McGuffin",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.580,
    duprSingles: 6.350,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0014",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jack-sock",
    name: "Jack Sock",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.550,
    duprSingles: 6.533,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0015",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-john-goins",
    name: "John Goins",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.200,
    duprSingles: 6.518,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0016",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-ammar-wazir",
    name: "Ammar Wazir",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.180,
    duprSingles: 6.517,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0017",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-roscoe-bellamy",
    name: "Roscoe Bellamy",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.210,
    duprSingles: 6.486,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0018",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-connor-garnett",
    name: "Connor Garnett",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.310,
    duprSingles: 6.448,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0019",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-zane-ford",
    name: "Zane Ford",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.150,
    duprSingles: 6.431,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0020",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-zane-navratil",
    name: "Zane Navratil",
    gender: "nam",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.320,
    duprSingles: 6.410,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-0021",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-quang-duong",
    name: "Quang Dương",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 6.450,
    duprSingles: 6.350,
    pvnaDoubles: 5.069,
    pvnaSingles: 3.000,
    pvnaId: "TPB0KO42",
    duprId: "DUPR-VN-0001",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-ly-hoang-nam",
    name: "Lý Hoàng Nam",
    gender: "nam",
    club: "Hải Đăng Tây Ninh",
    province: "Hồ Chí Minh",
    duprDoubles: 6.267,
    duprSingles: 5.920,
    pvnaDoubles: 4.774,
    pvnaSingles: 3.000,
    pvnaId: "CAYJAR",
    duprId: "DUPR-VN-0002",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-bao-duong",
    name: "Bảo Dương",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 5.850,
    duprSingles: 5.600,
    pvnaDoubles: 5.000,
    pvnaSingles: 3.000,
    pvnaId: "XJPE6A6J",
    duprId: "DUPR-VN-0003",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-trinh-linh-giang",
    name: "Trịnh Linh Giang",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.650,
    duprSingles: 5.500,
    pvnaDoubles: 4.650,
    pvnaSingles: 3.000,
    pvnaId: "VL4Y1X",
    duprId: "DUPR-VN-0004",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-truong-vinh-hien",
    name: "Trương Vinh Hiển",
    gender: "nam",
    club: "CLB D-Joy Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.620,
    duprSingles: 5.350,
    pvnaDoubles: 4.802,
    pvnaSingles: 3.000,
    pvnaId: "MHEM8H",
    duprId: "DUPR-VN-0005",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-joey-farias",
    name: "Joey Farias",
    gender: "nam",
    club: "Cần Thơ Pickleball",
    province: "Cần Thơ",
    duprDoubles: 5.600,
    duprSingles: 5.200,
    pvnaDoubles: 4.700,
    pvnaSingles: 3.000,
    pvnaId: "B6VORW4C",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-luc-pham",
    name: "Luc Pham",
    gender: "nam",
    club: "Pickleball Hồ Chí Minh",
    province: "Hồ Chí Minh",
    duprDoubles: 5.510,
    duprSingles: 5.300,
    pvnaDoubles: 4.250,
    pvnaSingles: 3.000,
    pvnaId: "LPH341",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-nguyen-viet-hoang",
    name: "Nguyễn Việt Hoàng",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.480,
    duprSingles: 5.250,
    pvnaDoubles: 4.200,
    pvnaSingles: 3.000,
    pvnaId: "NVH512",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-pham-minh-tuan",
    name: "Phạm Minh Tuấn",
    gender: "nam",
    club: "CLB Pickleball Đà Nẵng",
    province: "Đà Nẵng",
    duprDoubles: 5.450,
    duprSingles: 5.300,
    pvnaDoubles: 4.150,
    pvnaSingles: 3.000,
    pvnaId: "PMT102",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-nguyen-hoang-thien",
    name: "Nguyễn Hoàng Thiên",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.350,
    duprSingles: 5.200,
    pvnaDoubles: 4.180,
    pvnaSingles: 3.000,
    pvnaId: "NHT331",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-le-quoc-khanh",
    name: "Lê Quốc Khánh",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.320,
    duprSingles: 5.080,
    pvnaDoubles: 4.120,
    pvnaSingles: 3.000,
    pvnaId: "LQK204",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-nguyen-dac-tien",
    name: "Nguyễn Đắc Tiến",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.280,
    duprSingles: 5.120,
    pvnaDoubles: 4.100,
    pvnaSingles: 3.000,
    pvnaId: "NDT305",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-huynh-chi-khuong",
    name: "Huỳnh Chí Khương",
    gender: "nam",
    club: "CLB Kỳ Hòa Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.250,
    duprSingles: 5.050,
    pvnaDoubles: 4.100,
    pvnaSingles: 3.000,
    pvnaId: "HCK104",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-hoang-thanh-trung",
    name: "Hoàng Thành Trung",
    gender: "nam",
    club: "CLB Cầu Giấy Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.180,
    duprSingles: 5.020,
    pvnaDoubles: 4.080,
    pvnaSingles: 3.000,
    pvnaId: "HTT406",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-nathan-willis",
    name: "Nathan Willis",
    gender: "nam",
    club: "Andromeda Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 4.850,
    duprSingles: 4.620,
    pvnaDoubles: 4.050,
    pvnaSingles: 3.000,
    pvnaId: "NWL331",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "dupr-marcel-chan",
    name: "Marcel Chan",
    gender: "nam",
    club: "CLB Phú Nhuận",
    province: "Hồ Chí Minh",
    duprDoubles: 4.800,
    duprSingles: 4.650,
    pvnaDoubles: 4.020,
    pvnaSingles: 3.000,
    pvnaId: "MCH552",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },

  // --- Nữ Top DUPR (Đôi & Đơn) - Đồng bộ theo dashboard.dupr.com & dupr.com/rankings ---
  {
    id: "dupr-anna-leigh-waters",
    name: "Anna Leigh Waters",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.987,
    duprSingles: 6.453,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W001",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-anna-bright",
    name: "Anna Bright",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.598,
    duprSingles: 5.720,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W002",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-hurricane-tyra-black",
    name: "Hurricane Tyra Black",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.306,
    duprSingles: 5.750,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W003",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jorja-johnson",
    name: "Jorja Johnson",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.298,
    duprSingles: 5.650,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W004",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-parris-todd",
    name: "Parris Todd",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.273,
    duprSingles: 6.105,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W005",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-sofia-sewing",
    name: "Sofia Sewing",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.262,
    duprSingles: 6.004,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W006",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-rachel-rohrabacher",
    name: "Rachel Rohrabacher",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.238,
    duprSingles: 5.650,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W007",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jackie-kawamoto",
    name: "Jackie Kawamoto",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.231,
    duprSingles: 5.520,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W008",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-tina-pisnik",
    name: "Tina Pisnik",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.228,
    duprSingles: 5.480,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W009",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-jade-kawamoto",
    name: "Jade Kawamoto",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.188,
    duprSingles: 5.450,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W010",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-kate-fahey",
    name: "Kate Fahey",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.950,
    duprSingles: 6.175,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W011",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-catherine-parenteau",
    name: "Catherine Parenteau",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "Canada",
    duprDoubles: 6.175,
    duprSingles: 5.750,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-CA-W001",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-callie-smith",
    name: "Callie Smith",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.150,
    duprSingles: 5.620,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W012",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-etta-wright",
    name: "Etta Wright",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.120,
    duprSingles: 5.500,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W013",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-katerina-stewart",
    name: "Katerina Stewart",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.880,
    duprSingles: 6.043,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W014",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-lea-jansen",
    name: "Lea Jansen",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.080,
    duprSingles: 5.882,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W015",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-seone-mendez",
    name: "Seone Mendez",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.750,
    duprSingles: 5.875,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W016",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-brooke-buckner",
    name: "Brooke Buckner",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.820,
    duprSingles: 5.874,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W017",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-kaitlyn-christian",
    name: "Kaitlyn Christian",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.810,
    duprSingles: 5.864,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W018",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-kiora-kunimoto",
    name: "Kiora Kunimoto",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.650,
    duprSingles: 5.801,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W019",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-meghan-dizon",
    name: "Meghan Dizon",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 6.080,
    duprSingles: 5.550,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W020",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-mary-brascia",
    name: "Mary Brascia",
    gender: "nu",
    club: "PPA Tour Pro",
    province: "USA",
    duprDoubles: 5.980,
    duprSingles: 6.120,
    pvnaDoubles: 0,
    pvnaSingles: 0,
    duprId: "DUPR-US-W021",
    isDuprPlayer: true,
    isPvnaPlayer: false,
  },
  {
    id: "dupr-sophia-phuong-anh",
    name: "Sophia Phương Anh",
    gender: "nu",
    club: "Tuyển trẻ Pickleball VN",
    province: "Hồ Chí Minh",
    duprDoubles: 4.850,
    duprSingles: 4.520,
    pvnaDoubles: 3.950,
    pvnaSingles: 3.000,
    pvnaId: "SPA882",
    duprId: "DUPR-VN-W001",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
];

/**
 * Danh sách VĐV PVNA lưu sẵn (Sao chép và đồng bộ 100% từ pvna.vn)
 * Không bao giờ chứa Ben Johns, Anna Leigh Waters,... vì đây là hệ thống Việt Nam
 */
export const OFFICIAL_PVNA_PLAYERS: RatedPlayer[] = [
  {
    id: "pvna_tpb0ko42",
    name: "Quang Dương",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 6.450,
    duprSingles: 6.680,
    pvnaDoubles: 5.069,
    pvnaSingles: 3.000,
    pvnaId: "TPB0KO42",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_xjpe6a6j",
    name: "Bảo Dương",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 5.850,
    duprSingles: 5.600,
    pvnaDoubles: 5.000,
    pvnaSingles: 3.000,
    pvnaId: "XJPE6A6J",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_mhem8h",
    name: "Trương Vinh Hiển",
    gender: "nam",
    club: "CLB D-Joy Sài Gòn",
    province: "Hồ Chí Minh",
    duprDoubles: 5.620,
    duprSingles: 5.350,
    pvnaDoubles: 4.802,
    pvnaSingles: 3.000,
    pvnaId: "MHEM8H",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_cayjar",
    name: "Lý Hoàng Nam",
    gender: "nam",
    club: "Hải Đăng Tây Ninh",
    province: "Hồ Chí Minh",
    duprDoubles: 6.267,
    duprSingles: 5.920,
    pvnaDoubles: 4.774,
    pvnaSingles: 3.000,
    pvnaId: "CAYJAR",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_b6vorw4c",
    name: "Joey Farias",
    gender: "nam",
    club: "Cần Thơ Pickleball",
    province: "Cần Thơ",
    duprDoubles: 5.600,
    duprSingles: 5.200,
    pvnaDoubles: 4.700,
    pvnaSingles: 3.000,
    pvnaId: "B6VORW4C",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_vl4y1x",
    name: "Trịnh Linh Giang",
    gender: "nam",
    club: "Pickleball Hà Nội",
    province: "Hà Nội",
    duprDoubles: 5.650,
    duprSingles: 5.500,
    pvnaDoubles: 4.650,
    pvnaSingles: 3.000,
    pvnaId: "VL4Y1X",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: true,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_uul45a",
    name: "phương",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.424,
    pvnaSingles: 3.000,
    pvnaId: "UUL45A",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_6i86auh9",
    name: "Mikar Fisher",
    gender: "nam",
    club: "Nghệ An Pickleball",
    province: "Nghệ An",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.380,
    pvnaSingles: 3.000,
    pvnaId: "6I86AUH9",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_ecupqe",
    name: "Xuân Đức",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.352,
    pvnaSingles: 3.000,
    pvnaId: "ECUPQE",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_0zrqom",
    name: "Đỗ Minh Quân",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.307,
    pvnaSingles: 3.000,
    pvnaId: "0ZRQOM",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_ips0mxsn",
    name: "Jason Taylor",
    gender: "nam",
    club: "Cần Thơ Pickleball",
    province: "Cần Thơ",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.300,
    pvnaSingles: 3.000,
    pvnaId: "IPS0MXSN",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_j3kxyj",
    name: "Huy",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.300,
    pvnaSingles: 3.000,
    pvnaId: "J3KXYJ",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_sk4sdfpc",
    name: "Mayur Patrul",
    gender: "nam",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.291,
    pvnaSingles: 3.000,
    pvnaId: "SK4SDFPC",
    tickColor: "yellow",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_r2v67k",
    name: "Lê Ngọc Bảo",
    gender: "nam",
    club: "Đà Nẵng Pickleball",
    province: "Đà Nẵng",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.265,
    pvnaSingles: 3.000,
    pvnaId: "R2V67K",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_run5mq3m",
    name: "phan văn phúc",
    gender: "nam",
    club: "Hải Phòng Pickleball",
    province: "Hải Phòng",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 4.261,
    pvnaSingles: 3.000,
    pvnaId: "RUN5MQ3M",
    tickColor: "green",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  // VĐV Loan từ hệ thống thực PVNA (Ảnh tra cứu thực tế)
  {
    id: "pvna_v1slxt",
    name: "Đỗ Phương Loan",
    gender: "nu",
    club: "Hải Phòng Pickleball",
    province: "Hải Phòng",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.700,
    pvnaSingles: 2.400,
    pvnaId: "V1SLXT",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_s83c760c",
    name: "Loan",
    gender: "nam",
    club: "Đắk Lắk Pickleball",
    province: "Đắk Lắk",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.600,
    pvnaSingles: 2.600,
    pvnaId: "S83C760C",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_tm13en",
    name: "Hứa Mỹ Loan",
    gender: "nu",
    club: "Cần Thơ Pickleball",
    province: "Cần Thơ",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.479,
    pvnaSingles: 2.400,
    pvnaId: "TM13EN",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_udeemsms",
    name: "Trần Minh Loan",
    gender: "nu",
    club: "Hà Nội Pickleball",
    province: "Hà Nội",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.300,
    pvnaSingles: 2.100,
    pvnaId: "UDEEMSMS",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_d123mtlm",
    name: "loanlee (Loan)",
    gender: "nu",
    club: "Hồ Chí Minh Pickleball",
    province: "Hồ Chí Minh",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.235,
    pvnaSingles: 2.100,
    pvnaId: "D123MTLM",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_nv3gie",
    name: "Loan Su",
    gender: "nu",
    club: "Lâm Đồng Pickleball",
    province: "Lâm Đồng",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.231,
    pvnaSingles: 2.100,
    pvnaId: "NV3GIE",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_h389qen9",
    name: "Loan huỳnh",
    gender: "nu",
    club: "An Giang Pickleball",
    province: "An Giang",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.223,
    pvnaSingles: 2.100,
    pvnaId: "H389QEN9",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_m3j4dx",
    name: "Loan Huynh",
    gender: "nu",
    club: "Đồng Nai Pickleball",
    province: "Đồng Nai",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.182,
    pvnaSingles: 2.100,
    pvnaId: "M3J4DX",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
  {
    id: "pvna_effrpgvg",
    name: "Loan Trần",
    gender: "nu",
    club: "Lâm Đồng Pickleball",
    province: "Lâm Đồng",
    duprDoubles: 0,
    duprSingles: 0,
    pvnaDoubles: 2.176,
    pvnaSingles: 2.100,
    pvnaId: "EFFRPGVG",
    tickColor: "gray",
    tickColorSingle: "gray",
    isDuprPlayer: false,
    isPvnaPlayer: true,
  },
];

/**
 * Tra cứu bảng xếp hạng DUPR lưu sẵn
 */
export function getDuprLeaderboard(mode: "doi" | "don", query = ""): RatedPlayer[] {
  const norm = normalizeVietnamese(query);
  const filtered = OFFICIAL_DUPR_PLAYERS.filter((p) => {
    if (!p.isDuprPlayer) return false;
    if (norm) {
      const matchName = normalizeVietnamese(p.name).includes(norm);
      const matchId = p.duprId ? normalizeVietnamese(p.duprId).includes(norm) : false;
      return matchName || matchId;
    }
    if (mode === "doi" && p.duprDoubles <= 0) return false;
    if (mode === "don" && p.duprSingles <= 0) return false;
    return true;
  });

  return filtered.sort((a, b) => {
    const scoreA = mode === "doi" ? (a.duprDoubles || a.duprSingles) : (a.duprSingles || a.duprDoubles);
    const scoreB = mode === "doi" ? (b.duprDoubles || b.duprSingles) : (b.duprSingles || b.duprDoubles);
    return scoreB - scoreA;
  });
}

/**
 * Tra cứu bảng xếp hạng PVNA lưu sẵn (không bao giờ có VĐV quốc tế như Ben Johns)
 */
export function getPvnaLeaderboard(mode: "doi" | "don", query = ""): RatedPlayer[] {
  const norm = normalizeVietnamese(query);
  const filtered = OFFICIAL_PVNA_PLAYERS.filter((p) => {
    if (!p.isPvnaPlayer) return false;
    if (norm) {
      const matchName = normalizeVietnamese(p.name).includes(norm);
      const matchId = p.pvnaId ? normalizeVietnamese(p.pvnaId).includes(norm) : false;
      return matchName || matchId;
    }
    if (mode === "doi" && p.pvnaDoubles <= 0) return false;
    if (mode === "don" && p.pvnaSingles <= 0) return false;
    return true;
  });

  return filtered.sort((a, b) => {
    const scoreA = mode === "doi" ? (a.pvnaDoubles || a.pvnaSingles) : (a.pvnaSingles || a.pvnaDoubles);
    const scoreB = mode === "doi" ? (b.pvnaDoubles || b.pvnaSingles) : (b.pvnaSingles || b.pvnaDoubles);
    return scoreB - scoreA;
  });
}

/**
 * Tra cứu trực tiếp thời gian thực từ cơ sở dữ liệu PVNA (pvna.vn)
 * Đồng bộ chính xác 100% dữ liệu điểm số và màu tích (vàng, xanh, xám)
 */
export async function searchLivePvnaPlayers(
  queryText: string,
  sortBy: "doubleScore" | "singleScore" = "doubleScore"
): Promise<RatedPlayer[]> {
  try {
    const q = queryText.trim();
    const url = q
      ? `/api/pvna-proxy?search=${encodeURIComponent(q)}&page=0&limit=50`
      : `/api/pvna-proxy?page=0&limit=60&sortBy=${sortBy}&order=desc`;

    const res = await fetch(url);
    if (!res.ok) return [];
    const data = await res.json();
    if (!data.success || !Array.isArray(data.data?.players)) return [];

    return data.data.players.map((item: any): RatedPlayer => {
      const pDoubles = Number(item.doubleScore ?? item.hardScoreDouble ?? 0);
      const pSingles = Number(item.singleScore ?? item.hardScoreSingle ?? 0);
      const cityName = item.city ? (CITY_NAMES[item.city] || item.city) : "Việt Nam";

      return {
        id: `pvna_live_${item.playerCode || item.id}`,
        name: item.name || item.nickName || "VĐV",
        gender: item.gender === "female" ? "nu" : "nam",
        club: `${cityName} Pickleball`,
        province: cityName,
        duprDoubles: 0,
        duprSingles: 0,
        pvnaDoubles: pDoubles,
        pvnaSingles: pSingles,
        pvnaId: item.playerCode || "",
        tickColor: item.tickColor || "gray",
        tickColorSingle: item.tickColorSingle || "gray",
        isDuprPlayer: false,
        isPvnaPlayer: true,
      };
    });
  } catch (e) {
    console.debug("Lỗi tra cứu PVNA trực tiếp:", e);
    return [];
  }
}

/** Tương thích hàm cũ */
export function searchRatedPlayers(query: string, options?: { limit?: number }): RatedPlayer[] {
  const norm = normalizeVietnamese(query);
  const combined = [...OFFICIAL_DUPR_PLAYERS, ...OFFICIAL_PVNA_PLAYERS];
  const list = combined.filter((p) => {
    if (!norm) return true;
    return (
      normalizeVietnamese(p.name).includes(norm) ||
      (p.pvnaId && normalizeVietnamese(p.pvnaId).includes(norm)) ||
      (p.duprId && normalizeVietnamese(p.duprId).includes(norm))
    );
  });
  return list.slice(0, options?.limit ?? 50);
}
